language: c

before_script:
    # install libsodium (needed for libtoxcore)
  - _libsodium_version=0.4.5
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - pushd libsodium
  - git checkout tags/${_libsodium_version} > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure --prefix=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd

    # install toxcore
  - git clone git://github.com/irungentoo/toxcore > /dev/null
  - pushd toxcore
  - autoreconf -i > /dev/null
  - ./configure --prefix=/usr --disable-testing --disable-ntox > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd

script: cmake . && make -j3
