dist: xenial
sudo: false
language: c

addons:
  apt:
    sources:
      - sourceline: 'deb https://weechat.org/ubuntu xenial main'
        key_url: https://haavard.me/files/weechat_signing_key.gpg
    packages:
      - weechat-dev

env:
  # install dependencies under $HOME because we don't have sudo
  - DEPENDENCY_DIR="$HOME/dependencies" \
    PKG_CONFIG_PATH="$DEPENDENCY_DIR/lib/pkgconfig:$PKG_CONFIG_PATH" \
    CFLAGS=-Werror \
    SODIUM_VERSION=1.0.16 \
    TOXCORE_VERSION=0.2.8

install:
  # install libsodium, required by libtoxcore
  - mkdir libsodium && pushd libsodium
    && curl -fSsL "https://download.libsodium.org/libsodium/releases/libsodium-$SODIUM_VERSION.tar.gz"
       | tar -xz --strip-components 1
    && ./configure --prefix="$DEPENDENCY_DIR"
    && make install
    && popd

  # install libtoxcore
  - mkdir c-toxcore && pushd c-toxcore
    && curl -fSsL "https://github.com/TokTok/c-toxcore/archive/v$TOXCORE_VERSION.tar.gz"
       | tar -xz --strip-components 1
    && cmake -DCMAKE_INSTALL_PREFIX="$DEPENDENCY_DIR" -DBUILD_AV_TEST=off
    && make install
    && popd

script:
  - mkdir build && cd build
  - cmake -DCMAKE_PREFIX_PATH:PATH="$DEPENDENCY_DIR" ..
  - make
