language: c

install:
  - _libsodium_version=0.7.0
  - _weechat_version=v1.0

    # install libjansson
  - sudo apt-get install libjansson-dev

    # install libsodium (needed for libtoxcore)
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - pushd libsodium
  - git checkout tags/${_libsodium_version} > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure --prefix=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd

    # install toxcore
  - git clone git://github.com/irungentoo/toxcore > /dev/null
  - pushd toxcore
  - autoreconf -i > /dev/null
  - ./configure --prefix=/usr --disable-testing --disable-ntox > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd

    # install weechat
  - git clone git://github.com/weechat/weechat > /dev/null
  - pushd weechat
  - git checkout tags/${_weechat_version} > /dev/null
  - mkdir build && cd build
  - cmake .. -DPREFIX=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd

script:
  - mkdir build && cd build
  - cmake ..
  - make -j3

