language: c

install:
  - _libsodium_version=0.7.0
  - _weechat_version=v1.0
  - _libjansson_version=v2.5

    # install libjansson
  - git clone git://github.com/akheron/jansson.git
  - pushd jansson
  - git checkout tags/${_libjansson_version}
  - autoreconf -i
  - ./configure --prefix=/usr
  - make -j3
  - sudo make install
  - popd

    # install libsodium (needed for libtoxcore)
  - git clone git://github.com/jedisct1/libsodium.git
  - pushd libsodium
  - git checkout tags/${_libsodium_version}
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j3
  - sudo make install
  - popd

    # install libtoxcore
  - git clone git://github.com/irungentoo/toxcore
  - pushd toxcore
  - autoreconf -i
  - ./configure --prefix=/usr --disable-testing --disable-ntox
  - make -j3
  - sudo make install
  - popd

    # install weechat
  - git clone git://github.com/weechat/weechat
  - pushd weechat
  - git checkout tags/${_weechat_version}
  - mkdir build && cd build
  - cmake .. -DPREFIX=/usr
  - make -j3
  - sudo make install
  - popd

script:
  - mkdir build && cd build
  - cmake ..
  - make -j3

